vich_uploader:
    db_driver: orm

    mappings:
        categories_image:
            uri_prefix: /uploads/images/category/
            upload_destination: '%kernel.project_dir%/public/uploads/images/category/'
            namer: Vich\UploaderBundle\Naming\Base64Namer