vich_uploader:
    db_driver: orm

    mappings:
        categories_image:
            uri_prefix: /uploads/images/category/
            upload_destination: '%kernel.project_dir%/public/uploads/images/category/'
            namer: Vich\UploaderBundle\Naming\Base64Namer
        products_image:
            uri_prefix: /uploads/images/products/
            upload_destination: '%kernel.project_dir%/public/uploads/images/products/'
            namer: Vich\UploaderBundle\Naming\Base64Namer
        banners_image:
            uri_prefix: /uploads/images/banners/
            upload_destination: '%kernel.project_dir%/public/uploads/images/banners/'
            namer: Vich\UploaderBundle\Naming\Base64Namer